FLUSH LOGS;
SET GLOBAL BINLOG_FORMAT=ROW;
SET GLOBAL BINLOG_ROW_IMAGE=FULL;
SET GLOBAL ENFORCE_GTID_CONSISTENCY = ON;
SET GLOBAL GTID_MODE=OFF_PERMISSIVE;
SET GLOBAL GTID_MODE=ON_PERMISSIVE;
SET GLOBAL GTID_MODE=ON;
SET GLOBAL binlog_rows_query_log_events=on;

/*!80000 ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '******' */;

FLUSH LOGS;
